Conectar con Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os

os.listdir('/content/drive/MyDrive')

Mounted at /content/drive

['DNI ANVERSO.jpg',
 'DNI REVERSO.jpg',
 'SD CANON',
 'corto ingles.mp4',
 'Video de Gaduación 2016.mp4',
 'Foto de Oliver',
 'Fotos Oliver ',
 'Fotos Los Patos',
 'Ruler',
 'Fotos',
 'Cambio4.wav',
 'Cambio_master.wav',
 'Nocturno Nº2 - Oliver Castilla.MOV',
 'Tabla_de_Gastos_Actualizada.xlsx',
 'AHORRO.gsheet',
 'Gastos CASA.gsheet',
 'Documento sin título (1).gdoc',
 'carta vecinos.gdoc',
 'Cronograma base.odt',
 'Simulación hipoteca.gsheet',
 'laboratorio_completo.docx',
 'laboratorio_completo-2.docx',
 'Abstract TFG.gdoc',
 'Teoría Búsqueda y Optimización.gdoc',
 'Colab Notebooks',
 'Grabación de pantalla 2025-02-24 a las 17.09.13.mov',
 'MUIAEI_AA_2025_02_06_Act2_Python.ipynb.txt',
 'TFG_signed.pdf',
 'Datos bancarios.xlsx',
 'TFG',
 'Borrador Plan de Emergencia Ante Sequía.gdoc',
 'Accidente Lubna ',
 'lubna.pdf',
 'Hoja de cálculo sin título (1).gsheet',
 'RULER-SYNTAGMA_FINAL.mp4',
 'Hoja de cálculo sin título.gsheet',
 'IMD vs LOS.gdoc',
 'PROYECTEA 2025 AC HOTEL.gdoc',
 'Plan de inversiones.gsheet',
 'Documento sin título.gdoc',
 'CV.docx',
 'ihsen.gdoc',
 'Ponderaciones CASA.gsheet',
 'NOCHE DE CUENTO ICOD 2026.gdoc',
 'TFM']

Definir ruta de archivos

In [ ]:
ruta_padrones = "/content/drive/MyDrive/TFM/padrones_isora"

Prueba con un archivo

In [ ]:
import pandas as pd

archivo_prueba = ruta_padrones + "/201.TXT"

df = pd.read_csv(
    archivo_prueba,
    sep="\t",
    encoding="latin1",
    dtype=str
)

df.head()

,cliente,documento,fech_emision,periodo,fec_lec_ant_1,lec_ant_1,fec_lec_act_1,lec_act_1,dif_dias_1,dif_lec_1,...,num_fra2,num_fra3,num_fra4,des_tip_uso,ord_ruta,des_mod_fra,des_clase_fra,lect_ant_r_1,lect_cont_ant_1,f_lec_cont_ant_1
0,000042,12102001P0000062,27/02/2020,201 ENE-FEB/20,20/12/2019,"452,000",18/02/2020,"458,000",60,"6,000",...,NaN,NaN,NaN,NaN,66,Periodica,Periodica,"452,000","452,000",20/12/2019 00:00:00
1,000044,12102001P0000063,27/02/2020,201 ENE-FEB/20,21/12/2019,"425,000",18/02/2020,NaN,59,0,...,NaN,NaN,NaN,NaN,67,Periodica,Periodica,NaN,NaN,21/12/2019 00:00:00
2,000045,12102001P0000064,27/02/2020,201 ENE-FEB/20,21/12/2019,"262,000",18/02/2020,NaN,59,0,...,NaN,NaN,NaN,NaN,69,Periodica,Periodica,NaN,NaN,21/12/2019 00:00:00
3,000046,12102001P0000065,27/02/2020,201 ENE-FEB/20,20/12/2019,"164,000",18/02/2020,"167,000",60,"3,000",...,NaN,NaN,NaN,NaN,70,Periodica,Periodica,"164,000","164,000",20/12/2019 00:00:00
4,000047,12102001P0000066,27/02/2020,201 ENE-FEB/20,20/12/2019,"1394,000",18/02/2020,"1430,000",60,"36,000",...,NaN,NaN,NaN,NaN,71,Periodica,Periodica,"1394,000","1394,000",20/12/2019 00:00:00

Comprobación de columnas disponibles

In [ ]:
print(df.shape)
print(df.columns.tolist())

(9782, 250)
['cliente', 'documento', 'fech_emision', 'periodo', 'fec_lec_ant_1', 'lec_ant_1', 'fec_lec_act_1', 'lec_act_1', 'dif_dias_1', 'dif_lec_1', 'm3_cons_1', 'tipo_inc_1', 'incidencia_1', 'tipo_consumo_1', 'm3_asig_1', 'fec_lec_ant_2', 'lec_ant_2', 'fec_lec_act_2', 'lec_act_2', 'dif_dias_2', 'dif_lec_2', 'm3_cons_2', 'tipo_inc_2', 'incidencia_2', 'tipo_consumo_2', 'm3_asig_2', 'fec_lec_ant_3', 'lec_ant_3', 'fec_lec_act_3', 'lec_act_3', 'dif_dias_3', 'dif_lec_3', 'm3_cons_3', 'tipo_inc_3', 'incidencia_3', 'tipo_consumo_3', 'm3_asig_3', 'fec_lec_ant_4', 'lec_ant_4', 'fec_lec_act_4', 'lec_act_4', 'dif_dias_4', 'dif_lec_4', 'm3_cons_4', 'tipo_inc_4', 'incidencia_4', 'tipo_consumo_4', 'm3_asig_4', 'm3_fact', 'cod_plant', 'plantilla', 'n_usuarios', 'cod_tip_fact', 'tipo_fact', 'm3_blq_1', 'imp_blq_1', 'm3_blq_2', 'imp_blq_2', 'm3_blq_3', 'imp_blq_3', 'm3_blq_4', 'imp_blq_4', 'm3_blq_5', 'imp_blq_5', 'm3_blq_6', 'imp_blq_6', 'm3_blq_7', 'imp_blq_7', 'm3_blq_8', 'imp_blq_8', 'm3_blq_9', 'imp_blq_9', 'm3_blq_10', 'imp_blq_10', 'C agua', 'C contad', 'concep_3', 'concep_4', 'concep_5', 'concep_6', 'concep_7', 'concep_8', 'concep_9', 'concep_10', 'concep_11', 'concep_12', 'concep_13', 'concep_14', 'concep_15', 'concep_16', 'concep_17', 'concep_18', 'concep_19', 'concep_20', 'concep_21', 'concep_22', 'concep_23', 'concep_24', 'concep_25', 'concep_26', 'concep_27', 'concep_28', 'concep_29', 'concep_30', 'concep_31', 'concep_32', 'concep_33', 'concep_34', 'concep_35', 'concep_36', 'concep_37', 'concep_38', 'concep_39', 'concep_40', 'concep_41', 'concep_42', 'concep_43', 'concep_44', 'concep_45', 'concep_46', 'concep_47', 'concep_48', 'concep_49', 'Otros', 'IGIC', 'base', 'total', 'nombre_completo', 'nombre', 'ape1', 'ape2', 'fech_alt_ctt', 'direccion', 'ruta', 'banco', 'suc', 'cod_ctabanc', 'dig_ctabanc', 'nif_cli', 'tit_corres', 'direc_corres', 'pobl_corres', 'cod_post', 'contador_1', 'fec_inst_1', 'cod_mar_cont_1', 'marca_1', 'calibre_1', 'cod_mod_cont1', 'des_mod_cont1', 'lec_inicio_1', 'lec_retiro_1', 'contador_2', 'fec_inst_2', 'cod_mar_cont_2', 'marca_2', 'calibre_2', 'cod_mod_cont2', 'des_mod_cont2', 'lec_inicio_2', 'lec_retiro_2', 'contador_3', 'fec_inst_3', 'cod_mar_cont_3', 'marca_3', 'calibre_3', 'cod_mod_cont3', 'des_mod_cont3', 'lec_inicio_3', 'lec_retiro_3', 'contador_4', 'fec_inst_4', 'cod_mar_cont_4', 'marca_4', 'calibre_4', 'cod_mod_cont4', 'des_mod_cont4', 'lec_inicio_4', 'lec_retiro_4', 'ajuste', 'm3_bonificados', 'valor1', 'valor2', 'valor3', 'valor4', 'valor5', 'valor6', 'valor7', 'valor8', 'valor9', 'valor10', 'valor11', 'valor12', 'valor13', 'valor14', 'valor15', 'valor16', 'valor17', 'valor18', 'valor19', 'valor20', 'cobrado', 'f_cobro', 'cod_pobl_sumi', 'pobl_sumi', 'cod_via_sum', 'des_cat_via_sum', 'cod_post_sum', 'des_prv_corres', 'tlf1', 'tlf2', 'fech_ini_domici', 'lect_ant_cont_sus_1', 'fec_ant_cont_sus_1', 'm3 C agua', 'valor22', 'valor23', 'valor24', 'valor25', 'valor26', 'valor27', 'valor28', 'valor29', 'valor30', 'num_fra', 'email', 'estado_ctt', 'f_ini_est_ctt', 'cod_tip_cli', 'des_tip_cli', 'cod_sub_tip_cli', 'des_sub_tip_cli', 'num_personas', 'fini_num_personas', 'cod_pto_suministro', 'des_tip_pto_sumin', 'ref_catastral', 'cod_acometida', 'cod_acometida_gis', 'num_recl', 'num_fra2', 'num_fra3', 'num_fra4', 'des_tip_uso', 'ord_ruta', 'des_mod_fra', 'des_clase_fra', 'lect_ant_r_1', 'lect_cont_ant_1', 'f_lec_cont_ant_1']

Columnas útiles

In [ ]:
columnas_utiles = [
    "cliente",
    "documento",
    "fech_emision",
    "periodo",
    "fec_lec_ant_1",
    "lec_ant_1",
    "fec_lec_act_1",
    "lec_act_1",
    "dif_dias_1",
    "dif_lec_1",
    "m3_cons_1",
    "tipo_inc_1",
    "incidencia_1",
    "tipo_consumo_1",
    "m3_asig_1",
    "m3_fact",
    "n_usuarios",
    "direccion",
    "ruta",
    "cod_pobl_sumi",
    "pobl_sumi",
    "cod_post_sum",
    "estado_ctt",
    "cod_tip_cli",
    "des_tip_cli",
    "cod_sub_tip_cli",
    "des_sub_tip_cli",
    "num_personas",
    "cod_pto_suministro",
    "des_tip_pto_sumin",
    "ref_catastral",
    "des_tip_uso",
    "ord_ruta"
]

Versión con columnas útiles

In [ ]:
columnas_existentes = [c for c in columnas_utiles if c in df.columns]

df_reducido = df[columnas_existentes].copy()

df_reducido.head()

,cliente,documento,fech_emision,periodo,fec_lec_ant_1,lec_ant_1,fec_lec_act_1,lec_act_1,dif_dias_1,dif_lec_1,...,cod_tip_cli,des_tip_cli,cod_sub_tip_cli,des_sub_tip_cli,num_personas,cod_pto_suministro,des_tip_pto_sumin,ref_catastral,des_tip_uso,ord_ruta
0,000042,12102001P0000062,27/02/2020,201 ENE-FEB/20,20/12/2019,"452,000",18/02/2020,"458,000",60,"6,000",...,1,Doméstica,100,General,NaN,42,Agua,NaN,NaN,66
1,000044,12102001P0000063,27/02/2020,201 ENE-FEB/20,21/12/2019,"425,000",18/02/2020,NaN,59,0,...,1,Doméstica,100,General,NaN,44,Agua,NaN,NaN,67
2,000045,12102001P0000064,27/02/2020,201 ENE-FEB/20,21/12/2019,"262,000",18/02/2020,NaN,59,0,...,1,Doméstica,100,General,NaN,45,Agua,NaN,NaN,69
3,000046,12102001P0000065,27/02/2020,201 ENE-FEB/20,20/12/2019,"164,000",18/02/2020,"167,000",60,"3,000",...,1,Doméstica,100,General,NaN,46,Agua,NaN,NaN,70
4,000047,12102001P0000066,27/02/2020,201 ENE-FEB/20,20/12/2019,"1394,000",18/02/2020,"1430,000",60,"36,000",...,1,Doméstica,100,General,NaN,47,Agua,NaN,NaN,71

Conversión de todos los archivos .txt en archivos .csv

In [ ]:
import glob
import os

archivos_txt = glob.glob(ruta_padrones + "/*.TXT")

lista_df = []

for archivo in archivos_txt:
    df = pd.read_csv(
        archivo,
        sep="\t",
        encoding="latin1",
        dtype=str
    )

    columnas_existentes = [c for c in columnas_utiles if c in df.columns]
    df = df[columnas_existentes].copy()

    nombre_archivo = os.path.basename(archivo)
    df["archivo_origen"] = nombre_archivo

    lista_df.append(df)

maestro_txt = pd.concat(lista_df, ignore_index=True)

maestro_txt.shape

(334381, 34)

Comprobaciones

In [ ]:
maestro_txt["periodo"].value_counts().sort_index()

periodo
201 ENE-FEB/20                 9782
202  MAR-ABR/20                9799
203  MAY-JUN/20                9834
204  JUL-AGO/20               10272
205  SEP-OCT/20                9868
206 NOV-DIC/20                 9897
221 ENE-FEB/22                10156
222 MAR-ABR/22                10170
223 MAY-JUN/22                10480
224 JUL-AGO/22                10238
225 SEP-OCT/22                10252
226  NOV-DIC/22               10552
231 ENE-FEB/23                10572
232 MAR-ABR/23                10299
233 MAY-JUN/23                10626
234  JUL-AGO/23               10643
235  SEP-OCT/23               10657
236  NOV-DIC/23               10672
241 ENE-FEB/24                10678
242 MAR-ABR/24                10694
243  MAY-JUN/24               10700
244  JUL-AGO/24               10714
245 SEP-OCT/24                10744
246  NOV-DIC/24               10731
251 ENE-FEB/25                10761
252 MAR-ABR/25                10783
253 MAY-JUN/25                10823
254 JUL-AGO/25                10487
255 SEP-OCT/25                10518
256 NOV-DIC /25               10524
261 ENE-FEB/26                10513
262 MAR-ABR/26                10942
Name: count, dtype: int64

In [ ]:
maestro_txt["periodo"].nunique()

32

In [ ]:
maestro_txt["cliente"].nunique()

12427

In [ ]:
maestro_txt.columns.tolist()

['cliente',
 'documento',
 'fech_emision',
 'periodo',
 'fec_lec_ant_1',
 'lec_ant_1',
 'fec_lec_act_1',
 'lec_act_1',
 'dif_dias_1',
 'dif_lec_1',
 'm3_cons_1',
 'tipo_inc_1',
 'incidencia_1',
 'tipo_consumo_1',
 'm3_asig_1',
 'm3_fact',
 'n_usuarios',
 'direccion',
 'ruta',
 'cod_pobl_sumi',
 'pobl_sumi',
 'cod_post_sum',
 'estado_ctt',
 'cod_tip_cli',
 'des_tip_cli',
 'cod_sub_tip_cli',
 'des_sub_tip_cli',
 'num_personas',
 'cod_pto_suministro',
 'des_tip_pto_sumin',
 'ref_catastral',
 'des_tip_uso',
 'ord_ruta',
 'archivo_origen']

In [ ]:
maestro_txt['des_tip_cli'].value_counts()

des_tip_cli
Doméstica                                   292281
Industrial                                   42086
Municipal                                        3
Name: count, dtype: int64

Exportar df a una base de datos maestra

In [ ]:
maestro_txt.to_csv(
    "/content/drive/MyDrive/TFM/dataset_maestro_completo.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

Comprobaciones

In [ ]:
maestro_txt["periodo"].value_counts().sort_index()

periodo
201 ENE-FEB/20                 9782
202  MAR-ABR/20                9799
203  MAY-JUN/20                9834
204  JUL-AGO/20               10272
205  SEP-OCT/20                9868
206 NOV-DIC/20                 9897
221 ENE-FEB/22                10156
222 MAR-ABR/22                10170
223 MAY-JUN/22                10480
224 JUL-AGO/22                10238
225 SEP-OCT/22                10252
226  NOV-DIC/22               10552
231 ENE-FEB/23                10572
232 MAR-ABR/23                10299
233 MAY-JUN/23                10626
234  JUL-AGO/23               10643
235  SEP-OCT/23               10657
236  NOV-DIC/23               10672
241 ENE-FEB/24                10678
242 MAR-ABR/24                10694
243  MAY-JUN/24               10700
244  JUL-AGO/24               10714
245 SEP-OCT/24                10744
246  NOV-DIC/24               10731
251 ENE-FEB/25                10761
252 MAR-ABR/25                10783
253 MAY-JUN/25                10823
254 JUL-AGO/25                10487
255 SEP-OCT/25                10518
256 NOV-DIC /25               10524
261 ENE-FEB/26                10513
262 MAR-ABR/26                10942
Name: count, dtype: int64

In [ ]:
maestro_txt.shape

(334381, 34)

In [ ]:
maestro_txt["pobl_sumi"].value_counts()

pobl_sumi
Guia de Isora    334370
Name: count, dtype: int64

In [ ]:
maestro_txt["des_tip_uso"].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
maestro_txt["ruta"].value_counts().head(20)

ruta
1 GUIA ALTO                    50269
4 PLAYA ALTO                   35379
7 ALCALA BAJO                  33780
21 FONSALIA Y PLAYA NUE.       32861
5 PLAYA BAJO                   28120
14 CHIO                        25557
8 ALCALA ALTO                  22543
13 PIEDRA HINCADA              15187
11 TEJINA                      12702
2 GUIA BAJO                    11310
23 CHIGUERGUE                   8390
12 AGUA DULCE                   7885
24 VARADERO                     6821
22 VERA DE ERQUES               6269
3 GUIA DISEMINADO               6144
15 CHIRCHE                      4566
SECTOR POZO JARAL ACOJEJA       3730
SECTOR CUEVA DEL POLVO          2832
17 ARIPE                        2467
SECTOR TEJINA                   2299
Name: count, dtype: int64